### ISSUE TITLE
Problemas con el componente matrix

### ISSUE THREAD

**Issue by Kaziuz** [unloquer/matrix-led-react#3]
El componente Led se alimenta del array de objetos _Arrayled2_ para disponer del numero que contiene en color para pintar el circulo. Cuando cada Led actualiza su state, manda eso por prop al componente matrix, este debería de cambiar de su state null a ceros y unos pero no pasa nada.

**Comment by brolin** [comment]
@Kaziuz no entiendo, pegá enlaces a las líneas del código donde eso pasa?

**Comment by brolin** [comment]
@Kaziuz acabo de hacer un push https://github.com/unloquer/matrix-led-react/commit/d8f7d8c852a8c58fa56ec68b47ed2d002a3a5fcf donde ya funciona los websockets. 

No entiendo porque el componente Matrix se inicializa con unos leds rojos, de donde se inicializa? 

Ya se inicializa en ceros y se actualiza. Creo que antes estaba bueno también, solo que no estaba inicializados en cero los elementos del array.
